version: "3.8"

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - chatbot-net
    restart: unless-stopped

  web:
    build: ./fastapi
    container_name: debate-api
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge

volumes:
  ollama_models:
    driver: local
